import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from "ui";
import { renderTwoNumberSum } from 'math-helpers';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Monorepo example {renderTwoNumberSum(5, 10)}</h1>
        <Button/>
      </div>
    </div>
  )
}

export default Home
